name: forecasts
channels:
  - conda-forge
  - defaults
dependencies:
  # python dependencies
  - python=3.12
  - pip
  - boto3
  - cfgrib
  - dask
  - eccodes
  - fastparquet
  - geopandas
  - natsort
  - netcdf4
  - networkx
  - numpy
  - numcodecs
  - pandas
  - polars
  - s3fs
  - xarray
  - zarr
  # system dependencies
  - awscli  # AWS CLI
  - nco  # NetCDF Operators
  - cdo  # Climate Data Operators
  - gh  # GitHub CLI
  # pip dependencies
  - pip:
      - basininflow==0.14.0
